[package]
name = "passguard"
version = "0.1.0"
authors = ["dm67x <dm67x@outlook.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
